mvccampproject/Controllers/AdminCatagoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntitFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;

namespace mvccampproject.Controllers
{
    public class AdminCatagoryController : Controller
    {
        CatagoryManager cm = new CatagoryManager(new EfCatagoryDal());
       
        public ActionResult Index()
        {
            var catagoryvalues = cm.GetList();
            return View(catagoryvalues);
        }

        [HttpGet]
        public ActionResult AddCatagory()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddCatagory(Catagory p)
        {
            CatagoryValidator catagoryvalidator = new CatagoryValidator();
            ValidationResult result = catagoryvalidator.Validate(p);
            if(result.IsValid) {
                cm.CatagoryAddBL(p);
                return RedirectToAction("Index");
            }
            else {
                foreach(var item in result.Errors) {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        public ActionResult Delete(int id)
        {
            var catagoryvalue = cm.GetID(id);
            cm.CatagoryDelete(catagoryvalue);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult EditCatagory(int id)
        {
            var catagoryvalue = cm.GetID(id);
            return View(catagoryvalue);
        }
        [HttpPost]
        public ActionResult EditCatagory(Catagory p)
        {
            cm.CatagoryUpdate(p);
            return RedirectToAction("Index");
        }
    }
}

mvccampproject/Controllers/CatagoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntitFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;

namespace mvccampproject.Controllers
{
    public class CatagoryController : Controller
    {
        CatagoryManager cm = new CatagoryManager(new EfCatagoryDal());
        // GET: Catagory
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetCatagoryList()
        {
            var catagoryvalues = cm.GetList();
            return View(catagoryvalues);
        }
        [HttpGet]
        public ActionResult AddCatagory()
        {
            return View();
        }


     [HttpPost]
        public ActionResult AddCatagory(Catagory p)
        {
            // cm.CatagoryADDBl(p);
            CatagoryValidator catagoryValidator = new CatagoryValidator();
            ValidationResult results = catagoryValidator.Validate(p);
            if(results.IsValid) {
                cm.CatagoryAddBL(p);
                return RedirectToAction("GetCatagoryList");
            }
            else {
                foreach(var item in results.Errors) {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
    }
}

mvccampproject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvccampproject.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Test()
        {
            return View();
        }

    }
}

mvccampproject/Controllers/IstatistikController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccessLayer.Concrate;

namespace mvccampproject.Controllers
{
    public class IstatistikController : Controller
    {
        // GET: Istatistik
        Context c = new Context();
        public ActionResult Index()
        {
            ViewBag.d1 = c.Catagories.Count();
            var value1 = c.Catagories.Where(a => a.CatagoryName == "Yazilim").Single().CatagoryID;
            ViewBag.d2 = c.Headings.Where(a => a.CatagoryID == value1).Count();
            ViewBag.d3 = (from x in c.Writers where x.WriterName.Contains("a") select x.WriterName).ToList().Count.ToString();
            var value2 = c.Headings.GroupBy(x => x.CatagoryID).OrderByDescending(y => y.Count()).Select(z => z.Key).FirstOrDefault();
            ViewBag.d4 = c.Catagories.Where(a => a.CatagoryID == value2).Single().CatagoryName;
            ViewBag.d5 = c.Catagories.Count(x => x.CatagoryStatus == true) - c.Catagories.Count(x => x.CatagoryStatus == false);
            return View();
        }
    }
}

mvccampproject/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvccampproject.Controllers
{
    public class TestController : Controller
    {
        // GET: Test
        public ActionResult Index()
        {
            return View();
        }

      
    }
}

mvccampproject/Views/AdminCatagory/AddCatagory.cshtml
@model EntityLayer.Concrete.Catagory
@{
    ViewBag.Title = "AddCatagory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
@using (Html.BeginForm("AddCatagory", "AdminCatagory", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kategori adi")
        @Html.TextBoxFor(x => x.CatagoryName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CatagoryName)
        <br /><br />
        @Html.Label("Aciklama yazin")
        @Html.TextAreaFor(x => x.CatagoryDescription, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CatagoryDescription)
        <br /><br />
        <button>kaydet</button>
    </div>      
    }

mvccampproject/Views/AdminCatagory/EditCatagory.cshtml
@model EntityLayer.Concrete.Catagory
@{
    ViewBag.Title = "EditCatagory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
@using(Html.BeginForm("EditCatagory","AdminCatagory",FormMethod.Post))
            {
               <div class="form-group">
                   @Html.Label("Kategori ID")  
                   @Html.TextBoxFor(x=>x.CatagoryID,new { @class = "form-control" }) 
                   <br />
                   @Html.Label("kategori adi")
                   @Html.TextBoxFor(x => x.CatagoryName, new { @class = "form-control" })
                   <br />
                   @Html.Label("Tesvir et")
                   @Html.TextAreaFor(x => x.CatagoryDescription,new { @class = "form-control" })
                   <br />
                   <button class="btn btn-success">Guncelle</button>
               </div>
            }

mvccampproject/Views/AdminCatagory/Index.cshtml
@using EntityLayer.Concrete
@model List<Catagory>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@{
    var i = 0;
}
<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>catagoryname</th>
        <th>Aciklama</th>
       
        <th>Sil</th>
        <th>Guncelle</th>
        <th>Basliklar</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.CatagoryID</td>
            <td>@item.Headings</td>
            <td>@item.CatagoryDescription</td>
           
           @{
            i++;
            }
            <td><a href=" /AdminCatagory/Delete/@item.CatagoryID" class="btn btn-danger">Sil</a></td>
            <td><a href="/AdminCatagory/EditCatagory/@item.CatagoryID" class="btn btn-warning">Guncelle</a></td>
            <td><a href="#" class="btn btn-primary">Basliklar</a></td>
        </tr>
        
    }
</table>
<h2>@i</h2>
<a href="/AdminCatagory/AddCatagory" class="btn btn-info">Yeni Kategori</a>

mvccampproject/Views/Catagory/AddCatagory.cshtml
@model EntityLayer.Concrete.Catagory
@{
    Layout = null;
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<h2>salam</h2>
<br />

@using (Html.BeginForm("AddCatagory","Catagory",FormMethod.Post))
            {
    <div class="form-group">
        @Html.Label("Kategori adi")
        @Html.TextBoxFor(x=>x.CatagoryName)
        @Html.ValidationMessageFor(x=>x.CatagoryName)
        <br /><br />
        @Html.Label("Aciklama yazin")
        @Html.TextBoxFor(x=>x.CatagoryDescription)
        @Html.ValidationMessageFor(x=>x.CatagoryDescription)
        <br /><br />
        <button>kaydet</button>

    </div>

            }

@*<form class="form-group" method="post">
    <input type="text" placeholder="Kategori adi" name="CatagoryName" class="form-control"/>
    <button class="btn btn-primary">ekle</button>
</form>*@

mvccampproject/Views/Catagory/GetCatagoryList.cshtml
@using EntityLayer.Concrete
@model List<Catagory>
@{
    Layout = null;
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>catagoryname</th>
        <th>Aciklama</th>

        <th>Sil</th>
        <th>Guncelle</th>
        <th>Basliklar</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.CatagoryID</td>
            <td>@item.CatagoryName</td>
            <td>@item.CatagoryDescription</td>

            <td><a href="#" class="btn btn-danger">Sil</a></td>
            <td><a href="#" class="btn btn-warning">Guncelle</a></td>
            <td><a href="#" class="btn btn-primary">Basliklar</a></td>
        </tr>
    }
</table>
<a href="/Catagory/AddCatagory" class="btn btn-info">Yeni Kategori</a>

mvccampproject/Views/Catagory/Index.cshtml
@{
    Layout = null;
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<h3>MVC-Kategoriya</h3>
<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>adi</th>
        <th>Aciklama</th>
        <th>durum</th>
        <th>Guncelle</th>
    </tr>
    <tr>
        <td>1</td>
        <td>Tehsil</td>
        <td>Aciklama Yaptik</td>
        <td>True</td>
        <td><button class="btn btn-success">Guncelle</button></td>
    </tr>
    <tr>
        <td>2</td>
        <td>Idman</td>
        <td>Aciklama Yaptik</td>
        <td>True</td>
        <td><button class="btn btn-success">Guncelle</button></td>

    </tr>
</table>
<button class="btn-info">Yeni Kategori</button>
<button class="btn-warning">Aciklama kismi</button>

mvccampproject/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>
<br />
<h3>qedir</h3>

mvccampproject/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

mvccampproject/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

mvccampproject/Views/Home/Test.cshtml
@{
    ViewBag.Title = "Test";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Test</h2>
<br />
<p>qedir</p>

mvccampproject/Views/Istatistik/Index.cshtml
@using EntityLayer.Concrete
@model List<Catagory>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<br />
<h2 style="text-align:center">Statistik</h2>

<br />
<div style="display:flex; justify-content:space-between">
    <div class="card text-white bg-danger mb-3" style="width: 20rem; height: 20rem">
        <div class="card-header" style="font-size:medium">Toplam Kategori Sayısı</div>
        <div class="card-body">
            <p class="card-text" style="font-size:3rem; text-align:center">@ViewBag.d1</p>
        </div>
    </div>
    <div class="card text-white bg-success mb-3" style="width: 20rem; height: 20rem">
        <div class="card-header" style="font-size:medium">Başlık tablosunda "Yazilim" kategorisine ait başlık sayısı</div>
        <div class="card-body">
            <p class="card-text" style="font-size:3rem; text-align:center">@ViewBag.d2</p>
        </div>
    </div>
    <div class="card text-white bg-danger mb-3" style="width: 20rem; height: 20rem">
        <div class="card-header" style="font-size:medium">Yazar adında 'a' harfi geçen yazar sayısı</div>
        <div class="card-body">
            <p class="card-text" style="font-size:3rem; text-align:center">@ViewBag.d3</p>
        </div>
    </div>
    <div class="card text-white bg-warning mb-3" style="width: 20rem; height: 20rem">
        <div class="card-header" style="font-size:medium"> En fazla başlığa sahip kategori adı</div>
        <div class="card-body">
            <p class="card-text" style="font-size:2.5rem; text-align:center">@ViewBag.d4</p>
        </div>
    </div>
    <div class="card text-white bg-info mb-3" style="width: 20rem; height: 20rem">
        <div class="card-header" style="font-size:medium">Kategori tablosunda durumu true olan kategoriler ile false olan kategoriler arasındaki sayısal fark</div>
        <div class="card-body">
            <p class="card-text" style="font-size:3rem; text-align:center">@ViewBag.d5</p>
        </div>
    </div>
</div>

mvccampproject/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>AdminLTE 3 | Dashboard 3</title>

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
    <!-- IonIcons -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to to the body tag
to get the desired effect
|---------------------------------------------------------|
|LAYOUT OPTIONS | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        
        <!-- Navbar -->
       
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="index3.html" class="brand-link">
                <img src="~/AdminLTE-3.0.4/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
                     style="opacity: .8">
                <span class="brand-text font-weight-light">AdminLTE 3</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/AdminLTE-3.0.4/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">Alexander Pierce</a>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
         with font-awesome or any other icon font library -->
                        <li class="nav-item has-treeview menu-open">
                            <a href="#" class="nav-link ">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Catagories

                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="./index.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Dashboard</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="./index2.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Dashboard v2</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="./index3.html" class="nav-link active">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Dashboard v3</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a href="pages/widgets.html" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Headings

                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-copy"></i>
                                <p>
                                    Writers

                                </p>
                            </a>

                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-chart-pie"></i>
                                <p>
                                    Charts
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="pages/charts/chartjs.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Pie Chart</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/charts/flot.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Column Chart</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/charts/inline.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Line Charts</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-tree"></i>
                                <p>
                                    About

                                </p>
                            </a>

                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i>
                                <p>
                                    Contact & Message

                                </p>
                            </a>

                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-table"></i>
                                <p>
                                    Yazilar

                                </p>
                            </a>

                        </li>
                        <li class="nav-header">EXAMPLES</li>
                        <li class="nav-item">
                            <a href="pages/calendar.html" class="nav-link">
                                <i class="nav-icon fas fa-calendar-alt"></i>
                                <p>
                                    Yetkilendirme
                                    <span class="badge badge-info right">2</span>
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="pages/gallery.html" class="nav-link">
                                <i class="nav-icon far fa-image"></i>
                                <p>
                                    Gallery
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon far fa-envelope"></i>
                                <p>
                                    Error Page
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>

                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-book"></i>
                                <p>
                                    Siteye git

                                </p>
                            </a>

                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-door-closed"></i>
                                <p>
                                    Exit

                                </p>
                            </a>

                        </li>


                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
           
            <!-- /.content-header -->
            <!-- Main content -->
            <div class="content">
                @RenderBody();
                <!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Control Sidebar -->
        
        <!-- /.control-sidebar -->
        <!-- Main Footer -->
      
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE -->
    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.js"></script>

    <!-- OPTIONAL SCRIPTS -->
    <script src="~/AdminLTE-3.0.4/plugins/chart.js/Chart.min.js"></script>
    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>
    <script src="~/AdminLTE-3.0.4/dist/js/pages/dashboard3.js"></script>
</body>
</html>

mvccampproject/Views/Shared/_Deneme.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_Deneme</title>
</head>
<body>
	<div>
        layout
    </div>
	<div>dasdas</div>
    <div> 
        @RenderBody()
    </div>
</body>
</html>

mvccampproject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

mvccampproject/Views/Test/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Deneme.cshtml";
}

<h2>Index</h2>